site_name: مستندات پیشرفته API
site_url: https://yourdomain.com/api-docs/
site_description: |-
  مستندات جامع و حرفه‌ای برای API سرویس ما
  با نمونه‌کدهای آماده در زبان‌های مختلف

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.indexes
    - navigation.sections
    - navigation.top
    - navigation.expand
    - navigation.footer
    - navigation.path
    - search.highlight
    - search.suggest
    - toc.integrate
    - content.tabs
    - content.code.annotate
    - header.autohide
  palette:
    - scheme: default
      primary: deep purple
      accent: amber
      toggle:
        icon: material/weather-sunny
        name: حالت شب
    - scheme: slate
      primary: deep purple
      accent: amber
      toggle:
        icon: material/weather-night
        name: حالت روز
  font:
    text: Vazir
    code: Fira Code
  logo: assets/logo.png
  favicon: assets/favicon.ico

repo_url: https://github.com/yourusername/your-repo
repo_name: <i class="fab fa-github"></i> مخزن کد
edit_uri: edit/main/docs/

extra:
  social:
    - icon: fontawesome/brands/telegram
      link: https://t.me/yourchannel
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/yourhandle
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/company/yourcompany
  analytics:
    provider: google
    property: UA-XXXXXXXX-X
  api:
    base_url: https://api.yourdomain.com/v2
    version: 2.1.0
    contact: api-support@yourdomain.com
    license:
      name: MIT
      url: https://opensource.org/licenses/MIT

markdown_extensions:
  - admonition
  - attr_list
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __line
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.mark
  - pymdownx.caret
  - pymdownx.tilde
  - toc:
      permalink: ""
      baselevel: 2
      separator: "_"

plugins:
  - search
  - git-revision-date-localized:
      type: datetime
      timezone: Asia/Tehran
  - minify:
      minify_html: true
  - macros

nav:
  - صفحه نخست:
      - معرفی: index.md
      - تغییرات اخیر: changelog.md
  - شروع کار:
      - راهنمای نصب: getting-started/installation.md
      - احراز هویت: getting-started/authentication.md
      - نمونه سریع: getting-started/quickstart.md
  - نقاط پایانی:
      - کاربران:
          - مدیریت کاربران: endpoints/users/manage.md
          - احراز هویت: endpoints/users/auth.md
          - پروفایل: endpoints/users/profile.md
      - محصولات:
          - لیست محصولات: endpoints/products/list.md
          - جستجو: endpoints/products/search.md
          - مدیریت: endpoints/products/manage.md
      - سفارشات: endpoints/orders.md
      - پرداخت: endpoints/payment.md
  - نمونه‌کدها:
      - Python: samples/python.md
      - JavaScript: samples/javascript.md
      - PHP: samples/php.md
      - cURL: samples/curl.md
  - راهنما:
      - خطاها: guide/errors.md
      - استانداردها: guide/standards.md
      - امنیت: guide/security.md
  - سوالات متداول: faq.md
  - درباره:
      - تیم ما: about/team.md
      - تماس با ما: about/contact.md

extra_css:
  - css/custom.css
  - https://cdn.jsdelivr.net/gh/rastikerdar/vazir-font@v30.1.0/dist/font-face.css

extra_javascript:
  - js/custom.js
  - https://cdn.jsdelivr.net/npm/mermaid@10/dist/mermaid.min.js